[project]
name = "patool"
version = "4.1.0"
requires-python = ">=3.12"
dependencies = []
# these values are set by setup.py
dynamic = ["authors", "classifiers", "description", "keywords", "license", "readme", "scripts", "urls"]

[project.optional-dependencies]
# optional features
argcompletion = [
  "argcomplete>=3.6.2",
]

# these modules are only needed for development
[dependency-groups]
dev = [
  # for upgrading the version number
  "bump2version==1.0.1",
  # Sphinx plugin for markdown parsing
  "myst-parser==5.1.0",
  # test optional functionality
  "patool[argcompletion]",
  # for testing
  "pytest==9.1.1",
  # plugin to run tests in random order
  "pytest-randomly==4.1.0",
  # plugin to run tests in parallel
  "pytest-xdist[psutil]==3.8.0",
  # check for new packages
  "python-update-checker==0.9.0",
  # for python code linting
  "ruff==0.16.5",
  # Markdown style checking and formatting
  "rumdl==0.2.62",
  # for using setuptools.setup() in setup.py
  "setuptools==84.0.0",
  # for generating the web page
  "sphinx==9.1.0",
  # reformat toml files
  "tombi==1.4.1",
  # for python type checking
  "ty==0.0.75",
  # for generating a Python .whl file
  "wheel==0.48.0",
  # for auditing github actions
  "zizmor==1.29.0",
]

[build-system]
requires = ["setuptools-reproducible>=0.1"]
build-backend = "setuptools_reproducible"

[tool.project]
# pin versions of Python and uv for development
python_version_dev = "3.14.7"
uv_version_dev = "0.12.9"

[tool.ty.environment]
# patool uses some imports and attributes that are only available on windows
# so set the type check platform to windows
python-platform = "win32"
# patool tries to import modules that are only available on Python >= 3.14
python-version = "3.14"
