.\"                                      -*- nroff -*-
.\" Copyright (C) 2010 Bastian Kleineidam
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.TH PATOOL "1" "February 2010" "patool"
.SH NAME
patool - simple manager for file archives of various types
.SH SYNOPSIS
 \fBpatool\fP (\fBextract\fP|\fBlist\fP|\fBtest\fP) [\fIoptions\fP] <\fIarchive-file\fP>...
 \fBpatool\fP \fBcreate\fP [\fIoptions\fP] <\fIarchive-file\fP> [\fIfiles\fP...]
 \fBpatool\fP \fBformats\fP [\fIoptions\fP]
.SH DESCRIPTION
Various archive types can be created, extracted, tested and listed by
\fBpatool\fP. The advantage of patool is its simplicity in handling archive
files without having to remember a myriad of programs and options.
.PP
The archive format is determined by the file(1) program and as a fallback
by the archive file extension.
.PP
\fBpatool\fP supports 7z (.7z), ACE (.ace), ALZIP (.alz), AR (.a),
ARC (.arc), ARJ (.arj),
BZIP2 (.bz2), CAB (.cab), compress (.Z), CPIO (.cpio), DEB (.deb), GZIP (.gz),
LRZIP (.lrz), LZH (.lha, .lzh), LZIP (.lz), LZMA (.lzma), LZOP (.lzo),
RPM (.rpm), RAR (.rar), TAR (.tar), XZ (.xz) and ZIP (.zip, .jar) formats.
It relies on helper applications to handle those archive formats
(for example bzip2 for BZIP2 archives).
.SH EXAMPLES
  \fBpatool extract archive.zip otherarchive.rar\fP
  \fBpatool test --verbose dist.tar.gz\fP
  \fBpatool list package.deb\fP
  \fPpatool create --verbose myfiles.zip file1.txt dir/\fP
.SH COMMANDS
Several commands and options are available.
.SS \fBextract\fP
Extract files from an archive. This is the default command if no
command was given.
.br
Often one wants to extract all files
in an archive to a single subdirectory.
However, some archives contain multiple files in their root
directories. The patool program overcomes this problem by
first extracting files to a unique (temporary) directory, and
then moving its contents back if possible. This also prevents
local files from being overwritten by mistake.
.br
All extracted files are checked that they are readable by the
current user.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Be verbose when extracting (if the helper application supports it).
.TP
\fB\-\-help\fP
Show help for this command.
.SS \fBlist\fP
List files in an archive.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Verbose archive listing (if the helper application supports it).
.TP
\fB\-\-help\fP
Show help for this command.
.SS \fBcreate\fP
Create an archive from given files. At least on of the given files to add
to the archive has to exist.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Verbose operation (if the helper application supports it).
.TP
\fB\-\-help\fP
Show help for this command.
.SS \fBtest\fP
Test files in an archive.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Verbose archive testing (if the helper application supports it).
.TP
\fB\-\-help\fP
Show help for this command.
.SS \fBformats\fP
Show all supported archive formats.
.TP
\fB\-\-help\fP
Show help for this command.
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
.SH COPYRIGHT
Copyright \(co 2010 Bastian Kleineidam
