# This workflow will install Python dependencies, and run tests with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/tutorials/build-and-test-code/python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and run tests

    strategy:
      fail-fast: false
      matrix:
        # See https://github.com/actions/runner-images for available OS images
        os: ["ubuntu-24.04", "macos-15", "windows-2025"]
        python-version: ["3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}
    steps:
    # https://github.com/actions/checkout
    # https://github.com/actions/checkout/releases/tag/v6.0.2
    - name: Checkout project
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    # https://docs.astral.sh/uv/guides/integration/github/
    # https://github.com/astral-sh/setup-uv
    # https://github.com/astral-sh/setup-uv/releases/tag/v8.0.0
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        version: "0.11.7"

    - name: Set UV_PYTHON to Python ${{ matrix.python-version }}
      if: runner.os == 'Linux'
      run: echo "UV_PYTHON=${PYTHON_VERSION}" >> $GITHUB_ENV
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}

    - name: Set UV_PYTHON to Python ${{ matrix.python-version }}
      if: runner.os == 'Windows'
      run: echo "UV_PYTHON=${env:PYTHON_VERSION}" >> $env:GITHUB_ENV
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}

    - name: Install Python ${{ matrix.python-version }}
      run: uv python install

    - name: Create virtual Python environment
      run: uv venv

    - name: Install ruff
      run: uv pip install ruff

    - name: Check linting errors
      run: uv run --no-sync ruff check setup.py patoolib tests doc/web/source

    - name: Check code formatting
      run: uv run --no-sync ruff format --check setup.py patoolib tests doc/web/source

    - name: Install archive programs on Linux
      if: runner.os == 'Linux'
      run: >
        sudo apt-get update &&
        sudo apt-get install --no-install-recommends --yes arc archmage arj binutils bzip2 cabextract lzip lz4 plzip clzip pdlzip cpio flac genisoimage lbzip2 libarchive-tools lhasa lrzip lzop ncompress nomarch pbzip2 p7zip-full rar rpm2cpio unzip unace unalz unar unrar sharutils tar xdms zip zopfli zstd

    - name: Install archive programs on Windows
      if: runner.os == 'Windows'
      run: winget install --id=Giorgiotani.Peazip --exact --disable-interactivity --accept-source-agreements --accept-package-agreements

    - name: Install pytest and modules
      run: uv pip install pytest pytest-xdist[psutil] pytest-randomly

    - name: Test with pytest
      run: uv run --no-sync pytest -s --full-trace --numprocesses auto tests/
